# Generated by Django 6.0.3 on 2026-04-18 14:49

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "cnpj",
                    models.CharField(
                        help_text="Format: XX.XXX.XXX/XXXX-XX",
                        max_length=18,
                        unique=True,
                        validators=[apps.core.validators.validate_cnpj],
                        verbose_name="CNPJ",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="address")),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Format: (XX) XXXXX-XXXX",
                        max_length=15,
                        validators=[apps.core.validators.validate_phone_number],
                        verbose_name="phone number",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
                "ordering": ["name"],
            },
        ),
    ]
