# Generated by Django 6.0.3 on 2026-04-18 14:49

import apps.supply_lot.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inspection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplyLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("quarantine", "Quarantine"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                        validators=[apps.supply_lot.validators.validate_status],
                        verbose_name="status",
                    ),
                ),
                (
                    "manufacturing_date",
                    models.DateField(verbose_name="manufacturing date"),
                ),
                ("expiration_date", models.DateField(verbose_name="expiration date")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "inspection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supply_lot",
                        to="inspection.inspection",
                        verbose_name="inspection",
                    ),
                ),
            ],
            options={
                "verbose_name": "supply lot",
                "verbose_name_plural": "supply lots",
                "ordering": ["-manufacturing_date"],
            },
        ),
    ]
