# Generated by Django 6.0.3 on 2026-04-18 14:49

import apps.supply.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("supply_label", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("reserved", "Reserved"),
                            ("in_use", "In Use"),
                            ("depleted", "Depleted"),
                            ("damaged", "Damaged"),
                        ],
                        default="available",
                        max_length=20,
                        validators=[apps.supply.validators.validate_status],
                        verbose_name="status",
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("unit", "Unit"),
                            ("box", "Box"),
                            ("pack", "Pack"),
                            ("bottle", "Bottle"),
                            ("liter", "Liter"),
                            ("milliliter", "Milliliter"),
                            ("gram", "Gram"),
                            ("kilogram", "Kilogram"),
                        ],
                        max_length=20,
                        validators=[apps.supply.validators.validate_unit_of_measure],
                        verbose_name="unit of measure",
                    ),
                ),
                (
                    "supply_label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplies",
                        to="supply_label.supplylabel",
                        verbose_name="supply label",
                    ),
                ),
            ],
            options={
                "verbose_name": "supply",
                "verbose_name_plural": "supplies",
                "ordering": ["supply_label__name"],
            },
        ),
    ]
