# Generated by Django 6.0.3 on 2026-04-18 14:49

import apps.account.validators
import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("manager", "Manager"),
                            ("technician", "Technician"),
                            ("auditor", "Auditor"),
                            ("operator", "Operator"),
                        ],
                        max_length=20,
                        validators=[apps.account.validators.validate_account_type],
                        verbose_name="account type",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        help_text="Format: XXX.XXX.XXX-XX",
                        max_length=14,
                        unique=True,
                        validators=[apps.account.validators.validate_cpf],
                        verbose_name="CPF",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="address")),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Format: (XX) XXXXX-XXXX",
                        max_length=15,
                        validators=[apps.core.validators.validate_phone_number],
                        verbose_name="phone number",
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account",
                        to="organization.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "account",
                "verbose_name_plural": "accounts",
                "ordering": ["user__username"],
            },
        ),
    ]
