# Generated by Django 6.0.3 on 2026-04-18 14:49

import apps.supply_label.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupplyLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "supply_label_type",
                    models.CharField(
                        choices=[
                            ("medication", "Medication"),
                            ("equipment", "Equipment"),
                            ("sterilization", "Sterilization"),
                            ("nutrition", "Nutrition"),
                            ("blood_product", "Blood Product"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        validators=[apps.supply_label.validators.validate_supply_type],
                        verbose_name="supply type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("disposable", "Disposable"),
                            ("reusable", "Reusable"),
                            ("implantable", "Implantable"),
                            ("diagnostic", "Diagnostic"),
                            ("therapeutic", "Therapeutic"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        validators=[apps.supply_label.validators.validate_category],
                        verbose_name="category",
                    ),
                ),
                (
                    "details",
                    models.TextField(blank=True, null=True, verbose_name="details"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
