# Generated by Django 6.0.3 on 2026-04-18 14:49

import apps.inspection.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_complete",
                    models.BooleanField(default=False, verbose_name="is complete"),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="completion date"
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspections",
                        to=settings.AUTH_USER_MODEL,
                        validators=[
                            apps.inspection.validators.validate_responsible_is_auditor
                        ],
                        verbose_name="responsible",
                    ),
                ),
            ],
            options={
                "verbose_name": "inspection",
                "verbose_name_plural": "inspections",
                "ordering": ["-date"],
            },
        ),
    ]
